# Generated by Django 3.2.3 on 2021-06-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210526_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='latiude',
            new_name='latitude',
        ),
    ]
