# Generated by Django 3.2.3 on 2021-06-01 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_latiude_hospital_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 22, 29, 544213)),
        ),
    ]
