# Generated by Django 3.2.3 on 2021-06-01 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210601_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 23, 6, 575459, tzinfo=utc)),
        ),
    ]
