# Generated by Django 3.2.3 on 2021-06-01 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_treatment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
