# Generated by Django 3.2.3 on 2021-06-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_treatment_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bed_availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='class_type',
            field=models.CharField(default='Z', max_length=1),
        ),
    ]
