# Generated by Django 3.2.3 on 2021-06-02 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210602_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='prediction_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
