# Generated by Django 3.2.3 on 2021-06-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210602_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='hospital',
        ),
        migrations.AddField(
            model_name='treatment',
            name='puskesmas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.puskesmas'),
            preserve_default=False,
        ),
    ]
