# Generated by Django 3.2.3 on 2021-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_hospital_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='immediacy',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='treatment',
            name='painscale',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='treatment',
            name='temperature',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='jenis_pengobatan',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
