# Generated by Django 3.2.3 on 2021-06-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210606_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
