# Generated by Django 3.2.3 on 2021-06-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_medical_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='puskesmas',
        ),
    ]
